### PR TITLE
Update Run Basic InaSAFE Material for Socialization Training

### PR DESCRIPTION
**Pull request by adissadis**
Hi Everyone,

This is update for Run Basic InaSAFE material in Socialisation training. Please review my PR and take a look if there's any error or warning.

Thank you.

cc:
@Charlotte-Morgan @iyan31 @timlinux @rduivenvoorde

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
hi @adissadis - i've reopened this. if you are happy, please merge this before you close.

**Comment by rduivenvoorde** [comment]
@adissadis builds cleanly \o/

should I merge this or wait for @Charlotte-Morgan work first?

**Comment by adissadis** [comment]
@rduivenvoorde i think need to merge PR from charlotte first

**Comment by rduivenvoorde** [comment]
@adissadis github shows an conflict now for this pr. Will you be be able to fix that?

**Pull request closed without merging**
