### PR TITLE
Update changelog.rst

### PR DESCRIPTION
**Pull request by Charlotte-Morgan**
Deleted some "new features" listed in error for version2.0.0
@mach0 - please confirm my edits

### CODE REVIEW

**Comment by timlinux** [comment]
@Charlotte-Morgan I would like to suggest that in pursuit of a single point of truth we replace this page with a link to https://github.com/AIFDR/inasafe/releases . 

@mach0 If @Charlotte-Morgan agrees will you do that. Either way we need to treat this ticket with highest priority. Thanks!

**Comment by Charlotte-Morgan** [comment]
@timlinux & @mach0 
can & will the common garden potential user access https://github.com/AIFDR/inasafe/releases without having a GitHub account or being scared away??

**Comment by mach0** [comment]
@Charlotte-Morgan just tried it with a user not even having an account on github .. yes every user out there can access the page .. but I don't know if the "style" of the github page will scare them away :)

**Comment by Charlotte-Morgan** [comment]
@mach0 - that is good news.
If i put my 'user friendlines' blinkers on i would have to say that I prefer the *.rst option for now and that its a -1 (has anyone ever done that before?) for the github version. sorry @timlinux

**Pull request merged**
